#pragma once

#include "resource.h"
#include <Windows.h>
#include <SDL3/SDL.h>
#include <SDL3/SDL_vulkan.h>
#include "volk/volk.h"
#include "vma/vk_mem_alloc.h"
#include <ktxvulkan.h>
#include <optional>
#include <expected>
#include <vector>
#include <span>
#include <fstream>
#include <array>
#include <deque>
#include <functional>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include "app/config/Config.h"
#include "app/utils/utils.h"
#include <tracy/Tracy.hpp>
#include <tracy/TracyVulkan.hpp>